name: E2E Tests Workflow

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    e2e-tests:
        runs-on: ubuntu-latest

        steps:
            # Checkout du code source depuis le dépôt GitHub
            - name: Checkout code
              uses: actions/checkout@v3

            #  Configuration de l'environnement Node.js avec mise en cache des dépendances
            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '16'

            # Installation des dépendances avec npm
            - name: Install dependencies
              run: npm ci

            #  Démarrer le serveur
            - name: Start server
              run: npm run dev &
              env:
                  CI: true

            # Attendre que le serveur soit prêt
            - name: Wait for Vite server to be ready
              run: npx wait-on http://localhost:5173

            # Exécuter les tests Cypress
            - name: Run Cypress tests
              uses: cypress-io/github-action@v5
              with:
                  start: npm run dev
                  wait-on: http://localhost:5173
                  browser: chrome

            # Sauvegarder les vidéos
            - name: Upload Cypress artifacts
              uses: actions/upload-artifact@v3
              with:
                  name: cypress-artifacts
                  path: cypress/videos/
