name: GitHub Actions Demo
on: [push]
jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Prettier
        run: pnpm prettier

      - name: Run ESLint
        run: pnpm lint

      - name: Build project
        run: pnpm build

      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }}"
